In [114]:
import numpy as np

In [19]:
# to create numpy array usig list

arr=np.array([1,2,3,4,45,5,55,5])
arr
type(arr)

arr1=np.array([1,2,"!2,12",12])
type(arr1)
np.shape(arr1)
np.ndim(arr1)

1

In [18]:
arr2=np.array(12)
arr2
np.shape(arr2)
np.ndim(arr2)


0

arr3=np.array(([1,2,4,5],[6,7,8,9]))
arr3
type(arr3)
np.shape(arr3)
np.ndim(arr3)
arr3.shape=(4,2)
arr3
arr3.resize(2,4)
arr3
arr3.resize(8,1)
arr3

In [21]:
arr4=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,0],[23,34]]])
arr4
np.shape(arr4)
np.ndim(arr4)
arr4.ndim
arr4.shape

(3, 2, 2)

In [30]:
arr5=np.arange(24)
arr5
arr5.resize(3,8)
arr5
arr5.shape=(4,6)
arr5
arr5.reshape(6,4)
arr5

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [43]:
arr6=np.zeros((4,5),dtype=int,order='C')
arr6

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [46]:
arr7=np.ones((3,2),dtype=float)
arr7
arr7.ndim

2

In [52]:
arr8=np.arange(-5,-11,-1)
arr8.resize(2,3)
arr8


arr9=np.arange(-10,1,2)
arr9.reshape(3,2)
# np.arange(start,stop,step)

array([[-10,  -8],
       [ -6,  -4],
       [ -2,   0]])

In [56]:
arr10=np.arange(15)
arr10[2:4]
arr10[::-1]
arr10[1:9:3]

array([1, 4, 7])

In [58]:
arr11=np.arange(5,2)
arr11

array([], dtype=int32)

In [59]:
arr12=np.arange(0,30,6)
arr12

array([ 0,  6, 12, 18, 24])

In [62]:
arr13=np.arange(0,1,0.1)
arr13
arr13.reshape(5,2)

array([[0. , 0.1],
       [0.2, 0.3],
       [0.4, 0.5],
       [0.6, 0.7],
       [0.8, 0.9]])

In [71]:
arr14=np.array([[1,2],[3,4]])
arr15=np.array([[5,6],[7,8]])

arr16=np.concatenate((arr14,arr15),axis=1)
arr16

np.hstack((arr14,arr15))
np.vstack((arr14,arr15))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [76]:
arr17=np.linspace(0,4.5,10)
arr17

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [77]:
arr18=np.linspace(0,9,24)
arr18

array([0.        , 0.39130435, 0.7826087 , 1.17391304, 1.56521739,
       1.95652174, 2.34782609, 2.73913043, 3.13043478, 3.52173913,
       3.91304348, 4.30434783, 4.69565217, 5.08695652, 5.47826087,
       5.86956522, 6.26086957, 6.65217391, 7.04347826, 7.43478261,
       7.82608696, 8.2173913 , 8.60869565, 9.        ])

In [86]:
arr19=np.arange(1,5)
arr20=np.arange(20,24)
arr21=arr19*arr20
arr21
arr22=arr21-arr20
arr22

arr23=arr21/arr19
arr23

arr24=arr21%np.arange(78,82)
arr24


array([20, 42, 66, 11])

In [93]:
arr25=np.arange(1,11)
arr26=np.arange(31,41)
arr25.resize(5,2)
arr26.resize(5,2)
arr27=arr25+arr26
arr27
arr25+np.array([1,25])

array([[ 2, 27],
       [ 4, 29],
       [ 6, 31],
       [ 8, 33],
       [10, 35]])

In [99]:
arr28=np.array([[23,12,1],[23,34,12]])
np.sort(arr28)


array([[ 1, 12, 23],
       [12, 23, 34]])

In [101]:

# both gets same results
arr28.transpose()
arr28.T

array([[23, 23],
       [12, 34],
       [ 1, 12]])

In [109]:
arr29=np.arange(12)
np.array_split(arr29,3)
np.array_split(arr29,5)

[array([0, 1, 2]),
 array([3, 4, 5]),
 array([6, 7]),
 array([8, 9]),
 array([10, 11])]

In [111]:
arr30=np.array([12,234,34,56])
fa=[]
for i in arr30:
    if i<35:
        fa.append(True)
    else:
        fa.append(False)
arr30[fa]
fa

[True, False, True, False]

In [121]:
np.random.randint(100,size=(3,5))

array([[98, 55, 74, 66, 10],
       [15, 23,  0, 75, 33],
       [58, 61,  2, 16, 95]])

In [128]:
np.random.choice(arr1)

'!2,12'